FROM %DIST_VERSION% AS samanamon
ENV TZ=America/New_York
ENV DEBIAN_FRONTEND="noninteractive" 
COPY apps.tar start.sh build_container.sh build_config.dat /opt/
WORKDIR /
RUN tar -xvf /opt/apps.tar; \
    rm /opt/apps.tar; \
    /opt/build_container.sh installall
ENTRYPOINT [ "./start.sh" ]