ARG UBUNTU_VERSION
FROM sammbuild:${UBUNTU_VERSION} AS sammbuild2
ENV DEBIAN_FRONTEND=noninteractive
COPY samm-1.0.0-1_amd64.deb /usr/src
RUN apt update; apt install -y -f /usr/src/samm-1.0.0-1_amd64.deb
WORKDIR /usr/src/nagiosinstall
CMD /bin/bash
